## Neuron

In [153]:
import numpy as np
np.random.seed(0)

class Neuron:
    def __init__(self, n_inputs):
        self.weights = 0.1 * np.random.randn(n_inputs) # multiplying with 0.1 to keep the range within (-1, 0, 1)
        self.bias = np.zeros((1))

    def activate(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.bias


In [154]:
n = Neuron(5)
n.activate([1,2,3,4,5])
n.output

array([2.38019435])

## Layer

In [155]:
import numpy as np
np.random.seed(0)

class Layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons) # multiplying with 0.1 to keep the range within (-1, 0, 1)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [156]:
X = [
    [1.2, 5.1, 2.1], # sample 1
    [2.4, 3.6, 4.8], #sample 2
]

layer1 = Layer(3, 5)
layer1.forward(X)
# print(layer1.output)

layer2 = Layer(5,2)
layer2.forward(layer1.output)

print(layer2.output)

[[-0.06612363  0.07729238]
 [-0.08872864  0.14923993]]


### Pytorch

In [157]:
# Linear
import torch
from torch import nn

m = nn.Linear(in_features=3, out_features=5)
out = m(torch.tensor(X))

n = nn.Linear(in_features=5, out_features=2)
n(out)

tensor([[-1.5767, -0.6136],
        [-1.1977, -1.1698]], grad_fn=<AddmmBackward0>)

In [158]:
# Sequential

s = nn.Sequential(
    nn.Linear(3, 5),
    nn.Linear(5, 2)
)

s(torch.tensor(X))

tensor([[0.3179, 0.0254],
        [0.6751, 0.2003]], grad_fn=<AddmmBackward0>)