# Activation Function

In [30]:
import numpy as np
np.random.seed(0) # in notebooks, this needs to be present in the cell where the random is being called

# new code
class Activation:
    def __init(self):
        pass
    def forward(self, inputs):
        pass

# ReLU function
class Act_ReLU(Activation):
    def forward(self, inputs):
        return np.maximum(0, inputs)

class Act_Tanh(Activation):
    def forward(self, inputs):
        return np.tanh(inputs)

class Act_Sigmoid(Activation):
    def forward(self, inputs):
        return 1/(1 + np.exp(-x))

class Act_Softmax(Activation):
    def forward(self, inputs):
        print(inputs)
        exp = np.exp(inputs)
        return exp / np.sum(exp)

# imported from notebook: 01-perceptron-layer.ipynb
class Layer:
    def __init__(self, n_inputs, n_neurons, activation_fn):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons) # multiplying with 0.1 to keep the range within (-1, 0, 1)
        self.biases = np.zeros((1, n_neurons))
        self.activation = activation_fn()  # new code - initialise the activation class

    def forward(self, inputs):
        # modified to execute the activation forward code
        self.output = self.activation.forward(np.array(np.dot(inputs, self.weights) + self.biases))
        

In [31]:
layer1 = Layer(3, 4, Act_ReLU)
layer1.forward([1,2,3])

layer2 = Layer(4, 5, Act_Tanh)
layer2.forward(layer1.output)
layer2.output

layer3 = Layer(5, 2, Act_Tanh)
layer3.forward(layer2.output)
layer3.output

soft = Act_Softmax()
soft.forward(layer3.output)

[[ 0.00554223 -0.00117924]]


array([[0.50168036, 0.49831964]])

### PyTorch

In [32]:
import torch
from torch import nn

model = nn.Sequential(
    nn.Linear(3, 4),
    nn.ReLU(),
    nn.Linear(4, 5),
    nn.Tanh(),
    nn.Linear(5, 2),
    nn.Sigmoid()
)

model(torch.tensor([1.,2.,3.]))

tensor([0.3630, 0.4340], grad_fn=<SigmoidBackward0>)